# Generated by Django 2.0.2 on 2020-03-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWorkDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carId', models.IntegerField(default=0)),
                ('regionCode', models.CharField(max_length=20)),
                ('deviceId', models.CharField(max_length=32)),
                ('workDate', models.CharField(max_length=20)),
                ('workMode', models.IntegerField(default=0)),
                ('surveyPoints', models.IntegerField(default=0)),
                ('disWork', models.CharField(max_length=50)),
                ('workType', models.IntegerField(default=0)),
                ('depth', models.CharField(max_length=30)),
                ('arg5', models.CharField(max_length=64)),
                ('quaRate', models.CharField(max_length=30)),
                ('identifyId', models.CharField(max_length=20)),
                ('areaVaild', models.CharField(max_length=30)),
                ('areaPlatform', models.CharField(max_length=30)),
                ('loc1', models.CharField(max_length=500)),
                ('loc2', models.CharField(max_length=500)),
                ('loc3', models.CharField(max_length=500)),
                ('loc4', models.CharField(max_length=500)),
                ('loc5', models.CharField(max_length=500)),
                ('beginTime', models.CharField(max_length=50)),
                ('endTime', models.CharField(max_length=50)),
                ('longitude', models.IntegerField(default=0)),
                ('latitude', models.IntegerField(default=0)),
                ('machineWidth', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=30)),
                ('arg3', models.CharField(max_length=30)),
                ('acrossDistrict', models.IntegerField(default=0)),
                ('districtCode', models.CharField(max_length=64)),
                ('areaDistrict', models.CharField(max_length=30)),
                ('areaVaildDistrict', models.CharField(max_length=30)),
                ('arg3District', models.CharField(max_length=30)),
                ('clientId', models.CharField(max_length=32)),
                ('distanceWear', models.CharField(max_length=30)),
                ('disWorkWear', models.CharField(max_length=30)),
                ('speed', models.CharField(max_length=4)),
                ('seedinRate', models.CharField(max_length=7)),
                ('missSeedingRate', models.CharField(max_length=7)),
                ('sprayQuantity', models.CharField(max_length=7)),
                ('stubbleHeight', models.CharField(max_length=7)),
                ('flag', models.IntegerField(default=0)),
                ('dayRow', models.CharField(max_length=30)),
                ('daySowingNumber', models.CharField(max_length=30)),
                ('sprayingNumber', models.CharField(max_length=30)),
                ('nklocation', models.CharField(max_length=255)),
                ('isNKCar', models.CharField(max_length=1)),
                ('dataState', models.CharField(max_length=1)),
                ('extStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
