# Generated by Django 2.0.2 on 2020-03-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carworkday',
            name='beginTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carworkday',
            name='endTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carworkday',
            name='workDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
