# Generated by Django 2.0.2 on 2020-04-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_routeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeinfo',
            name='data',
        ),
    ]
