# Generated by Django 2.0.2 on 2020-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20200512_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinfo',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='routeinfo',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='routeinfo',
            name='speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='routeinfo',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
