# Generated by Django 2.0.2 on 2020-05-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20200512_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machineid', models.CharField(max_length=30)),
                ('pointnum', models.IntegerField()),
                ('distance', models.FloatField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('worktype', models.CharField(choices=[('1', '插秧'), ('2', '深松')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='routeinfo',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='routeinfo',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routeinfo',
            name='workid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.Route'),
        ),
    ]
