# Generated by Django 2.0.2 on 2020-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20200519_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='pointnum',
            field=models.IntegerField(null=True),
        ),
    ]
