# Generated by Django 2.0.2 on 2020-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20200519_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinfo',
            name='deep',
            field=models.FloatField(default=0),
        ),
    ]
