# Generated by Django 2.0.2 on 2020-05-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_routeinfo_deep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='worktype',
            field=models.CharField(max_length=5),
        ),
    ]
