# Generated by Django 2.0.2 on 2020-05-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20200520_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinfo',
            name='course',
            field=models.FloatField(default=0),
        ),
    ]
