# Generated by Django 2.0.2 on 2020-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_routeinfo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinfo',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
