# Generated by Django 2.0.2 on 2020-05-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_auto_20200522_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carworkday',
            name='carId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carworkday',
            name='disWork',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='carworkday',
            name='workType',
            field=models.CharField(max_length=5),
        ),
    ]
