# Generated by Django 2.0.2 on 2020-05-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_auto_20200522_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='carworkday',
            name='workDate',
            field=models.DateField(null=True),
        ),
    ]
